name: 'Full CI/CD Workflow'

on:
  workflow_run:
    workflows:
      - 's3modifiedfile.yml'
    types: 
      - completed

#Set the environment variables for tracking metrics
env:
  #SFPOWERSCRIPTS_SPLUNK: 'true'
  #SFPOWERSCRIPTS_SPLUNK_HOST: '${{ secrets.SPLUNK_HOST }}'
  #SFPOWERSCRIPTS_SPLUNK_API_KEY : '${{ secrets.SPLUNK_INSIGHT_INSERT_KEYS }}'
  SFPOWERSCRIPTS_NEWRELIC: 'true'
  SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  SIT:
    runs-on: ubuntu-latest
    #container: ghcr.io/dxatscale/sfpowerscripts
    container: ghcr.io/dxatscale/sfpowerscripts
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    environment:
      name: SIT
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
   
      - name: Authenticate to SIT sandbox
        run: |
          echo "${{ secrets.SIT_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a sit

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      # Release to environment
      - name: 'Release to SIT'
        run: 'sfp orchestrator:release -u sit -p ./release-definitions/release-sit.yml  --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::" --loglevel=${{ vars.DX_LOGLEVEL_VALUE }}'
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


