name: Upload to S3

on:
  push:
    branches:
      - ref11
      - production

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Determine modified and deleted files
        id: diff
        run: |
          git fetch --no-tags --prune --depth=1 origin "+refs/heads/main:refs/remotes/origin/main"
          MODIFIED_FILES=$(git diff --name-only origin/main...$GITHUB_REF)
          DELETED_FILES=$(git diff --name-only --diff-filter=D origin/main...$GITHUB_REF)

      - name: Upload modified files to S3
        if: ${{ steps.diff.outputs.MODIFIED_FILES != '' }}
        run: |
          for file in ${{ steps.diff.outputs.MODIFIED_FILES.split('\n') }}; do
            if [[ "${{ github.ref }}" == "refs/heads/ref11" ]]; then
              aws s3 cp $file s3://testbucket240523/$file
            elif [[ "${{ github.ref }}" == "refs/heads/ref22" ]]; then
              aws s3 cp $file s3://testbucket240523/$file
            fi
          done

      - name: Delete deleted files from S3
        if: ${{ steps.diff.outputs.DELETED_FILES != '' }}
        run: |
          for file in ${{ steps.diff.outputs.DELETED_FILES.split('\n') }}; do
            if [[ "${{ github.ref }}" == "refs/heads/ref11" ]]; then
              aws s3 rm s3://testbucket240523/$file
            elif [[ "${{ github.ref }}" == "refs/heads/ref22" ]]; then
              aws s3 rm s3://testbucket240523/$file
            fi
          done
