name: Sync staging S3 bucket 

on:
  push:
    branches: ref11 # Need to modify (changing staging branch for testing)

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository ref11 Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ref11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-1'
      - name: Sync modified files to s3 
        uses: badsyntax/github-action-aws-s3@v1.0.2
        id: synced-files
        with: 
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          aws-region: 'eu-west-1'
          action: 'sync'
          src-dir: './*'
          files-glob: '*'
          sync-strategy: LastModified

      - name: Output Synced Files
        run: |
          echo "Synced object keys: $S3SyncedFiles"
        env:
          # Use outputs from previous sync steps
          S3SyncedFiles: ${{ steps.synced-files.outputs.modified-keys }}


#      - name: sync files to s3 
#        run: |
#          aws s3 sync . s3://${{ secrets.AWS_STAGING_BUCKET }} 
